### ISSUE TITLE
Estructurar el proyecto un poquito

### ISSUE THREAD

**Issue by oneeyedman** [oneeyedman/hola-halloween#3]
Qué rolli es ese de tener los archivos de cualquier manera?

No molaría más tener un proyecto más ordenado? en carpeticas? 

Por ejemplo, así:

```
.
├── CODE_OF_CONDUCT.md
├── CONTRIBUTING.md
├── README.md
├── assets
│   ├── css
│   │   └── hola.css
│   ├── docs
│   │   └── hf10_icon_fcd_rgb.png
│   └── js
│       └── hola.js
├── favicon.ico
├── humans.txt
└── index.html

```

Después habrá que ajustar las rutas en el HTML y en alguno de los MD ;)

**Comment by saura8668** [comment]
Hey @oneeyedman can I work on this?

**Comment by oneeyedman** [comment]
Yes, you can!!

**Comment by saura8668** [comment]
hey @oneeyedman made the proper folder structure. Please review the pull request

**Comment by oneeyedman** [comment]
YAY, @saura8668! Well done!!! ^^

**Comment by oneeyedman** [comment]
@saura8668 Feel free to add yourself to the humans.txt file ;) https://github.com/oneeyedman/hola-halloween/issues/5
